### ISSUE TITLE
强烈建议做成 UserCSS

### ISSUE THREAD

**Issue by Geeyun-JY3** [grasonchan/simple-zhihu#5]
强烈建议做成 UserCSS 并在 GitHub 和 Greasy Fork 分发

**Comment by grasonchan** [comment]
对 UserCSS 和 Greasy Fork 做了一些了解

发现：
1. UserCSS 尚未标准化
2. 支持 UserCSS 的扩展还较为有限
3. Greasy Fork 虽支持发布 UserCSS，但该网站更多的还是偏向 User Scripts，发现其首页也未有提及到 UserCSS
4. Greasy Fork 的搜索结果似乎只展示 `可转换为 UserJS 的 UserCSS`

转换为 UserCSS 并不难，主要是添加 `.user.css` 扩展名和元数据；Stylus 可对 UserCSS 文件进行安装和检查更新，**但是不支持 UserCSS 的浏览器扩展却是无法直接安装**

我发布在 Stylish 的样式暂时无需涉及脚本，且提供的自定义设置似乎无法在 Greasy Fork 提供；另外，该样式我是更偏向通用性，即在各系统、浏览器、Stylish 相关的扩展上都可以使用；故，初步的想法是不去进行支持

若有其它补充，烦请 comment，感谢建议！

**Comment by Geeyun-JY3** [comment]
提这个 issue 主要还是 Userstyles.org 太慢了，这还不是国内独有的……主要问题是访问困难、慢，导致设置更新起来太麻烦。
所以本 issue 重点是摆脱样式对 Userstyles.org 的依赖（自定义设置）。Stylus 也在 [v1.5.14](https://github.com/openstyles/stylus/releases/tag/v1.5.14)、[v1.5.16](https://github.com/openstyles/stylus/releases/tag/v1.5.16) 有很明显的摆脱对 Userstyles.org 的依赖的相关更新。

UserCSS 的设置（即对应在 Userstyles.org 上进行的设置）可以直接在 Stylus 扩展（本地）中进行，这和分发渠道无关。这也是我强烈建议做成 UserCSS 的原因。

建议通过 Greasy Fork 分发是顺便提的。Greasy Fork 确实也没支持多久 UserCSS，主要是方便国内用户下载。搜索结果这块我没怎么了解，是想着 TA 既然支持了 UserCSS 那也就能作为一个分发渠道。
GitHub 同样能分发，就是网络条件稍微麻烦点，而且网络条件也可以通过 jsDelivr 解决。It depends on you.

通用性的问题，我是觉得既然都知道用 Userstyle，应该多少听说过 [Stylish 扩展的黑历史](https://sspai.com/post/45537)，多数都转用 Stylus 或别的安全替代了。至于同类扩展是否支持 UserCSS，确实没怎么了解过，只知道 Firefox 还有个 [FireMonkey](https://addons.mozilla.org/en-US/firefox/addon/firemonkey/)。我开这个 issue 也有推广 UserCSS 的考虑（主要原因还是上面提到的本地就可以设置，方便太多了），你们作为样式开发者转用 UserCSS 也能让更多用户知道了解到 UserCSS，认识到其相比 Userstyles.org 的优势所在，推动更多用户使用 UserCSS，从而也能促进更多 Userstyle 管理器支持 UserCSS 这一格式。
当然我并不知道到底还有多少人在用 Stylish 和 Userstyles.org。只是我本人现在出于效率和长久性考虑主张远离 Userstyles.org，就 Userstyles.org 现在的情况看上去其并不可靠。
